import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import java.awt.event.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Scanner;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Akele Benjamin 620130803
 */
 public class Machine_ReportGUI extends javax.swing.JFrame {

     // Variables declaration - do not modify                     
    private javax.swing.JButton returnButton;
    private javax.swing.JButton makeReportBtn;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JPanel greetingPanel;
    private javax.swing.JPanel machineTablePanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JScrollPane mScrollPane;
    private javax.swing.JTable machinesTable;
    private DefaultTableModel model;
    private ArrayList<Machine> machinelist;
    // End of variables declaration      

    /**
     * Creates new form Machine_ReportGUI
     */
    public Machine_ReportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        //intiallize Components
        greetingPanel = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        greetingLabel = new javax.swing.JLabel();
        machineTablePanel = new javax.swing.JPanel();
        mScrollPane = new javax.swing.JScrollPane();
        machinesTable = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        makeReportBtn = new javax.swing.JButton();

        //Frame Settings
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(871, 612));

        //Greeting Panel Color
        greetingPanel.setBackground(new java.awt.Color(51, 102, 255));
        //Page Title
        pageTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(255, 255, 255));
        pageTitle.setText("Machine report Generator");
        //Greeting
        greetingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("Welcome User");

        //Greeting Panel Layout
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(greetingPanel);
        greetingPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(greetingLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        //Machine Panel Color
        machineTablePanel.setBackground(new java.awt.Color(255, 255, 255));

        //Machines Table
        machinelist=tableData("MachineListData.txt");
        
        String[] columnNames = { "Machine ID","Machine Type","Total Cycles","Cycles Today","Maintenance Request"};
        model=new DefaultTableModel(columnNames,0);
        machinesTable= new JTable(model);
        
        showTable(machinelist); //display table
        
        machinesTable.setPreferredScrollableViewportSize(new Dimension(600, machinelist.size()*15 +50));
        machinesTable.setFillsViewportHeight(true);

        mScrollPane = new JScrollPane(machinesTable);


        //Machine Panel Layout
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(machineTablePanel);
        machineTablePanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(mScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(mScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        //Button Panel Color
        btnPanel.setBackground(new java.awt.Color(255, 255, 255));

        //Return Home Button
        returnButton.setText("Return Home");
        returnButton.setBackground(new java.awt.Color(51, 102, 255));
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        //Make Report Button
        makeReportBtn.setText("Make a Report");
        makeReportBtn.setBackground(new java.awt.Color(51, 102, 255));
        makeReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        makeReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new Generate_Report().setVisible(true);
                dispose();
            }
        });

        //Button Panel Layout
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addGap(147, 147, 147)
                .addComponent(makeReportBtn)
                .addGap(262, 262, 262))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton)
                    .addComponent(makeReportBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        //Frame Layout
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(greetingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(machineTablePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(greetingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(machineTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>  
    
    private ArrayList<Machine> tableData(String file){
        Scanner mscan = null;
        ArrayList<Machine> mList = new ArrayList<Machine>();

        try{
            mscan  = new Scanner(new File(file));
            while(mscan.hasNext()){
                String data = mscan.nextLine(); 
                String[] nextLine = data.split(" ");
                //Output: FirstName Lastname CustomerID Date TotalAmount-Wash TotalAmount-Dry $Amount
                String mId=nextLine[0];
                String machineType=nextLine[1];
                int totCycles=Integer.parseInt(nextLine[2]);
                int dailyCycle=Integer.parseInt(nextLine[3]);
                Boolean machineRequest= Boolean.parseBoolean(nextLine[4]);
                
                Machine m=new Machine(mId,machineType,totCycles,dailyCycle,machineRequest);
                mList.add(m);
            }
            mscan.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,"An Error reading the Database","Error",JOptionPane.ERROR_MESSAGE);;
        }

        return mList;


    }
    
    private void showTable(ArrayList<Machine> mlist)
    {
        if (mlist.size()>0)
        {
            for(Machine m: mlist)
            {
                addToTable(m);
            }
        }
    }

    private void addToTable(Machine m)
    {
        //finish Customer Sale Class
        String[] machine={m.getMachineID(),""+m.getMachineType(),""+m.getUseCount(),""+m.getDailyUseCount(),""+m.getMaintenanceRequest(),""};
        model.addRow(machine);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Machine_ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Machine_ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Machine_ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Machine_ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Machine_ReportGUI().setVisible(true);
            }
        });
    }

                
}
